#!/bin/bash

CONFIG=$1
if [ "${CONFIG}" = "" ]; then
  CONFIG=/etc/default/abstrakt-registry
fi

if [[ -f "${DEFAULT}" ]]; then
  . ${DEFAULT}
else
  HOSTNAME=localhost
  PORT=5984
  LOGFILE=
  LOGLEVEL=info
  REGISTRYPATH=
fi

node lib/server.js
