#!/bin/sh
### BEGIN INIT INFO
# Provides:          nopar
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: NOPAR - The Node PAckage Registry & proxy
# Description:       NOPAR - The Node PAckage Registry & proxy
### END INIT INFO

# set -e

# /etc/init.d/nopar: start and stop the NOPAR Node Package Registry

test -x /usr/bin/nopar || exit 0

umask 022

export NOPAR_RUN_AS=nopar

if test -f /etc/default/nopar; then
  . /etc/default/nopar
fi

. /lib/lsb/init-functions

if [ -n "$2" ]; then
    NOPAR_OPTS="$NOPAR_OPTS $2"
fi

# Are we running from init?
run_by_init() {
  ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
}

check_lib_dir() {
  # Create the lib empty dir if necessary
  if [ ! -d /var/lib/nopar ]; then
    mkdir /var/lib/nopar
    chmod 0755 /var/lib/nopar
    chown ${NOPAR_RUNAS_USER} /var/lib/nopar
  fi
}

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
    check_lib_dir
    log_daemon_msg "Starting NOPAR Server ${NOPAR_HOSTNAME}:${NOPAR_PORT}" "nopar" || true
    if start-stop-daemon --start --quiet --oknodo --pidfile ${NOPAR_RUN_PATH}/nopar.pid --exec /usr/bin/nopar -- $NOPAR_OPTS; then
      log_end_msg 0 || true
    else
      log_end_msg 1 || true
    fi
  ;;

  stop)
    log_daemon_msg "Stopping NOPAR Server" "nopar" || true
    if start-stop-daemon --stop --quiet --oknodo --pidfile ${NOPAR_RUN_PATH}/nopar.pid; then
      log_end_msg 0 || true
    else
      log_end_msg 1 || true
    fi
  ;;

  reload|force-reload)
    log_daemon_msg "Reloading NOPAR Server" "nopar" || true
    if start-stop-daemon --stop --signal 1 --quiet --oknodo --pidfile ${NOPAR_RUN_PATH}/nopar.pid --exec /usr/bin/nopar; then
      log_end_msg 0 || true
    else
      log_end_msg 1 || true
    fi
  ;;

  restart)
    check_lib_dir
    log_daemon_msg "Restarting NOPAR Server" "nopar" || true
    start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile ${NOPAR_RUN_PATH}/nopar.pid
    sleep 1
    if start-stop-daemon --start --quiet --oknodo --pidfile ${NOPAR_RUN_PATH}/nopar.pid --exec /usr/bin/nopar -- $NOPAR_OPTS; then
      log_end_msg 0 || true
    else
      log_end_msg 1 || true
    fi
  ;;

  status)
    status_of_proc -p ${NOPAR_RUN_PATH}/nopar.pid /usr/bin/nopar nopar && exit 0 || exit $?
  ;;

  *)
  log_action_msg "Usage: /etc/init.d/ssh {start|stop|restart|status}" || true
  exit 1
esac

exit 0
