#!/bin/bash
set -e

PKG_NAME=`node -e 'process.stdout.write(require("./package.json").name);'`
PKG_VERSION=`node -e 'process.stdout.write(require("./package.json").version);'`
PKG=${PKG_NAME}-${PKG_VERSION}

echo "==== Packaging ${PKG_NAME}@${PKG_VERSION} ===="

rm -fr nopar*.tgz .latest.id node_modules
npm install --production

GNU_TAR=`tar --version | grep GNU`
if [ "${GNU_TAR}" = "" ]; then
  TAR="tar -c -s ,^,${PKG}/,"
else
  TAR="tar -c --transform s,^,${PKG}/,"
fi

echo ${PKG} > .latest.id
$TAR --owner=root --group=root -z -f ${PKG}.tgz \
 bin \
 lib \
 node_modules \
 public \
 scripts \
 views \
 package.json \
 README.md

echo "==== Packaged ${PKG}.tgz ===="
