#!/bin/bash
set -e

PKG_NAME=`node -e 'process.stdout.write(require("./package.json").name);'`
PKG_VERSION=`node -e 'process.stdout.write(require("./package.json").version);'`
PKG=${PKG_NAME}-${PKG_VERSION}

echo "==== Packaging ${PKG_NAME}@${PKG_VERSION} ===="

rm -fr nopar*.tgz .latest.id node_modules
npm install --production

echo ${PKG} > .latest.id
tar -c --owner=root --group=root -z -f ${PKG}.tgz \
 bin \
 lib \
 node_modules \
 public \
 scripts \
 views \
 package.json \
 README.md

mkdir ${PKG}
cd ${PKG}
tar -x -f ../${PKG}.tgz
cd ..
rm -f ${PKG}.tgz
tar -c --owner=root --group=root -z -f ${PKG}.tgz ${PKG}
rm -fr ${PKG}

echo "==== Packaged ${PKG}.tgz ===="
