#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export PKG_NAME=`node -e 'process.stdout.write(require("./package.json").name);'`
export PKG_VERSION=`node -e 'process.stdout.write(require("./package.json").version);'`
export PKG_DESCRIPTION=`node -e 'process.stdout.write(require("./package.json").description);'`
export PKG=${PKG_NAME}_${PKG_VERSION}

if [ "${RELEASE_BUILD}" == "yes" ] || [ "${BUILD_NUMBER}" == "" ]; then
  echo "== This is a RELEASE_BUILD"
else
  PKG_VERSION=${PKG_VERSION}-b${BUILD_NUMBER}
  PKG=${PKG_NAME}_${PKG_VERSION}
fi

$DIR/prepackage
$DIR/package-tgz
$DIR/package-deb
