#!/bin/bash
set -e

if [ "$PKG_NAME" == "" ]; then
  echo "ERROR: PKG_NAME not set"
  exit 5
fi

if [ "$PKG_VERSION" == "" ]; then
  echo "ERROR: PKG_VERSION not set"
  exit 5
fi

if [ "$PKG_DESCRIPTION" == "" ]; then
  echo "ERROR: PKG_DESCRIPTION not set"
  exit 5
fi

if [ "$PKG" == "" ]; then
  echo "ERROR: PKG not set"
  exit 5
fi

if [ "${BUILD_NUMBER}" == "" ]; then
  echo "== No build information available"
  HOSTNAME=`hostname -f`
  BUILD_NUMBER=0
  BUILD_ID="${USER}@${HOSTNAME}"
  BUILD_URL=""
fi

echo "== Adding build information to package"
echo "BUILD_NUMBER : ${BUILD_NUMBER}"
echo "BUILD_ID     : ${BUILD_ID}"
echo "BUILD_URL    : ${BUILD_URL}"
cp package.json package.orig.json
node > package.json <<EOF
var pkg = require("./package.orig.json");
pkg.build = {
  number : "${BUILD_NUMBER}",
  id     : "${BUILD_ID}",
  url    : "${BUILD_URL}"
};
console.log(JSON.stringify(pkg, null, "\t"));
EOF
rm package.orig.json
